var email = "catwhiskers9@msn.com"
var book = "dune"
var song = "strawberry swing"
var age = 31
var speed = 60
var numBudgies = 2
var isPercyBlue = true
var isLemonBlue = false
var isLemonYellow = true